class HwConfig:
    Y_PRIORITY = True

    CHIP_X_MIN = 0
    CHIP_X_MAX = 0
    CHIP_Y_MIN = 0
    CHIP_Y_MAX = 0

    N_BIT_CORE_X = 5
    N_BIT_CORE_Y = 5

    CORE_X_MIN = 0
    CORE_X_MAX = (1 << N_BIT_CORE_X) - 1
    CORE_Y_MIN = 0
    CORE_Y_MAX = (1 << N_BIT_CORE_Y) - 1

    N_CORE_OFFLINE = 1008
    CORE_X_OFFLINE_MIN = CORE_X_MIN
    CORE_Y_OFFLINE_MIN = CORE_Y_MIN
    CORE_X_OFFLINE_MAX = 28
    CORE_Y_OFFLINE_MAX = 28
    CORE_X_ONLINE_MIN = 29
    CORE_Y_ONLINE_MIN = 29
    CORE_X_ONLINE_MAX = CORE_X_MAX
    CORE_Y_ONLINE_MAX = CORE_Y_MAX

    N_AXON_DEFAULT = 1152
    N_NEURON_DEFAULT = 512
    N_TIMESLOT_MAX = 256

    N_SUB_ROUTER_NODE = 4
