name: Release Drafter

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v4

      - name: Update poetry.lock
        run: poetry update --lock

      - run: echo "TAG_NAME=v$(poetry version -s)" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v6
        with:
          name: ${{ env.TAG_NAME }}
          tag: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
